### PR TITLE
Make GitHub CI better to automate the generation of contributor lists

### PR DESCRIPTION
**Pull request by alamin655**
## What does this PR do?
This PR enables automated updating of the contributors' list in the `README.md` file. It introduces the `contributors-list` action from `wow-actions` (uses: `wow-actions/contributors-list@v1`) to automate the process of updating the list of contributors. This improvement streamlines the maintenance of the contributors' list, ensuring it stays up to date without manual intervention.

## Why is this change important?
This PR introduces an automated solution to update the contributors' list in the `README.md` file. By utilizing the `wow-actions/contributors-list@v1` action, project maintainers can now effortlessly keep the list up to date without manual intervention. This enhancement simplifies the process of fetching and displaying the contributors' information, enhancing the overall maintenance experience.

image

## How to test this PR locally?
You can test this PR locally by cloning the repository, checking out the `rolling`, and running the workflow locally to verify that the contributors' list in the `README.md` file is updated correctly.

### CODE REVIEW

**Comment by alamin655** [comment]
@neon-mmd / @XFFXFF Hey, if you approve it, just merge it using squash so that it only shows 1 commit instead of 19.

**Comment by neon-mmd** [comment]
> @neon-mmd / @XFFXFF Hey, if you approve it, just merge it using Squash so that it only shows 1 commit instead of 19.

I love the changes you made and thanks for taking the time to work on it but I disagree with the changes you made because I would prefer to have contributors list avatars to have a round shape and without names because I feel it adds less noise and looks better :slightly_smiling_face:, What are your thoughts on this ?? 

> Also a few things to take note of:
> 
> 1. The commit message I feel is not very descriptive which makes it hard to know what each is specifically changing in the code, What do you think??
> 2. The fixes/closes micros only work on issues, not on PRs :slightly_smiling_face:.

**Comment by alamin655** [comment]
> > @neon-mmd / @XFFXFF Hey, if you approve it, just merge it using Squash so that it only shows 1 commit instead of 19.
> 
> I love the changes you made and thanks for taking the time to work on it but I disagree with the changes you made because I would prefer to have contributors list avatars to have a round shape and without names because I feel it adds less noise and looks better 🙂, What are your thoughts on this ??

I appreciate your suggestions, and I have made the necessary fixes based on your feedback. Regarding the shape and inclusion of names, I don't have a strong preference. The most important thing is that the contributor list is displayed accurately. Thank you for your input!
> > Also a few things to take note of:
> > 
> > 1. The commit message I feel is not very descriptive which makes it hard to know what each is specifically changing in the code, What do you think??
> > 2. The fixes/closes micros only work on issues, not on PRs 🙂.
1. Message updated.
2. Noted, thanks!

**Review by neon-mmd — CHANGES_REQUESTED** [review]
It looks like this will not work because we have `branch protection rules` set up on different branches and this will not allow the changes to be committed directly as it requires putting a PR for the changes. Also, for better context on this issue, you can review issue #4 of the [contributors-list](https://github.com/wow-actions/contributors-list) project :slightly_smiling_face: .

**Comment by alamin655** [comment]
> It looks like this will not work because we have `branch protection rules` set up on different branches and this will not allow the changes to be committed directly as it requires putting a PR for the changes. Also, for better context on this issue, you can review issue #4 of the [contributors-list](https://github.com/wow-actions/contributors-list) project 🙂 .

I have branch protection on in my fork but it's working for me.

**Comment by neon-mmd** [comment]
Why did you close this PR ?? any specific reasons for it?? if so can you please mention in brief your decision for doing so :slightly_smiling_face: .

**Pull request closed without merging**
