### PR TITLE
Configure MegaLinter for automated code linting

### LINKED ISSUE #107: Automate all checks for `linting/formatting` for different language using a single GitHub action
Automate the process of checking all formatting, linting and spelling issues using a GitHub action called [MegaLinter](https://github.com/marketplace/actions/megalinter).

The linters/formatters/spell checker that should be included:
- **Linters**
   - Lua -- [luacheck](https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/lua_luacheck.md)
   - Rust -- [clippy](https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/rust_clippy.md)
   - JavaScript -- [eslint](https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/javascript_eslint.md)
- **Formatters**
   - Css -- [stylelint](https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/css_stylelint.md)
   - Markdown -- [markdownlint](https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/markdown_markdownlint.md)
   - Yaml -- [yamllint](https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/yaml_yamllint.md)
   - Html -- [djlint](https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/html_djlint.md)
- **Tooling**
   - actions -- [actionlint](https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/action_actionlint.md)
   - dockerfile -- [hadolint](https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/dockerfile_hadolint.md)
- **Spell Checker**
   - spelling -- [cspell](https://github.com/oxsecurity/megalinter/tree/main/docs/descriptors/spell_cspell.md)

### PR DESCRIPTION
**Pull request by alamin655**
## What does this PR do?
This pull request adds a GitHub Actions workflow configuration file for the MegaLinter. The MegaLinter is a powerful code linting tool that checks the codebase for various programming languages and file types, ensuring consistent code quality and style across the project.

## Why is this change important?
This change is important because it introduces automated code linting to the CI/CD pipeline. By incorporating the MegaLinter, we can identify and fix code quality issues early in the development process. This helps maintain code consistency, reduces the likelihood of bugs, and improves overall code maintainability.

## Author's checklist
- [x] Reviewed the MegaLinter configuration file for accuracy and completeness.
- [x] Ensured that the workflow triggers on both push events and pull requests to the rolling branch.
- [x] Set up the environment variables for applying linter fixes as specified in the configuration.
- [x] Tested the workflow locally to verify its functionality.
- [x] Documented any notable changes or considerations in the pull request description.

## Related issues
Closes #107

### CODE REVIEW

**Comment by neon-mmd** [comment]
Thanks for working on this and putting in the effort, Everything looks good :+1: , but I would suggest doing one thing before we can merge this PR. Can you please bump the `Cargo.toml` version number to v0.12.4 if you haven't merged PR #110 or v0.13.1 if PR #110 has been merged. :slightly_smiling_face:

**Comment by neon-mmd** [comment]
The build GitHub action seems to fail, to fix this I would suggest running something like this (as shown below in the code snippet) to update the `Cargo.lock` file and then adding a new commit to this PR with the change.

``` shell
cargo generate-lockfile
cargo build
```

**Review by neon-mmd — CHANGES_REQUESTED** [review]
Also, one more thing I would like to suggest before we merge this in :slightly_smiling_face: , can you remove the `global variables` warnings by writing a JSON file for it? Because the `rlua` crate expects that every variable in Lua code should be global, otherwise there is no way to grab variable values from Lua code as yet :slightly_smiling_face: .

**Comment by alamin655** [comment]
> Also, one more thing I would like to suggest before we merge this in 🙂 , can you remove the `global variables` warnings by writing a JSON file for it? Because the `rlua` crate expects that every variable in Lua code should be global, otherwise there is no way to grab variable values from Lua code as yet 🙂 .

Okay sure, you seem to be right, I will go with your suggestion :slightly_smiling_face: .

**Comment by alamin655** [comment]
**Update**
- changed image to `cupcake` (reduce size by `48.375451263538%` compared to default image)
- removed `lua` check
- bumped to `version = "0.13.13"`

**Review by neon-mmd — APPROVED** [review]
Thanks :heart: for working on this and putting in all the effort :slightly_smiling_face: . I will merge this PR right away :rocket: .

**Pull request merged**
