### PR TITLE
🛠️ Some major fixes

### PR DESCRIPTION
**Pull request by PhantomMorrigan**
## What does this PR do?

make some code more readable.

Also fixes a bug where requests did a blocking sleep in async code (seriously?) and a vulnerability where an attacker could crash the server by sending request with invalid search engine names in the cookie, causing the aggregate function to panic it's thread, making ddos attacks very easy to execute.

## Why is this change important?

Fixes some major bugs

## Related issues

progress on both #180 and #178 

Note: currently a dependency causes a clippy warning, causing the ci to always fail.

### CODE REVIEW

**Comment by PhantomMorrigan** [comment]
Also: the megalint ci task failing is not my fault, it failed in the version i pulled from here

**Comment by alamin655** [comment]
Thank you for the PR. While running, I don't see any logs like before.

**Comment by PhantomMorrigan** [comment]
Must have broken that while refactoring it, will fix it soon.

**Comment by PhantomMorrigan** [comment]
should be fixed now

**Comment by alamin655** [comment]
Also, can you bump the version to v0.17.0?

**Comment by alamin655** [comment]
> Also: the megalint ci task failing is not my fault, it failed in the version i pulled from here

No worries; the megalinter lints will be fixed soon.

**Review by alamin655 — CHANGES_REQUESTED** [review]
Can you bump the app version to v0.17.0?

**Comment by PhantomMorrigan** [comment]
had to also set remove the wild card version selectors, for some reason they broke when i changed the version

**Comment by alamin655** [comment]
> had to also set remove the wild card version selectors, for some reason they broke when i changed the version

I don't know, but it's working just fine for me.

**Review by alamin655 — CHANGES_REQUESTED** [review]
https://discord.com/channels/1101871027669192754/1104074375315062865/1142376869451284501

**Review by alamin655 — APPROVED** [review]

**Review by alamin655 — APPROVED** [review]
Approved! Let's merge this in. 👍

**Comment by neon-mmd** [comment]
Thanks :heart: for working on such a wonderful PR. I really appreciate it :+1: keep it up!! Hope to see you soon with cool PRs like this in future :slightly_smiling_face: .

**Pull request merged**
