### PR TITLE
Centered About page content

### LINKED ISSUE #59: Make about page centered
Put some margins on the right and left of the content of the `About Page` to make it centered on the website to make it visually look better by using percentage values for the margins instead of using fixed values like `rem`, `em`, `px`, etc. 

image

The target file that needs to be changed is located under `public/static/themes` and it is called `simple.css`.

### PR DESCRIPTION
**Pull request by sam-sunder**
## Why is this change important?
This PR fixes https://github.com/neon-mmd/websurfx/issues/59 centering about page content

This is an UI fix

## Related issues
Closes #59

### CODE REVIEW

**Comment by sam-sunder** [comment]
image

**Comment by neon-mmd** [comment]
I don't why but the `About page` content doesn't seem to be centered, Maybe you made a slight error or mistake in the code for example `you wanted to add something else but mistakenly added something other than what was intended`, I would suggest reviewing the code once more :slightly_smiling_face: .

image

**Comment by sam-sunder** [comment]
Thanks, I've reviewed code and found the mistake. It's ready to be reviewed by you now 😊

**Review by neon-mmd — APPROVED** [review]
Now it looks perfect :+1: !! I will merge this change right away :slightly_smiling_face: .

**Pull request merged**
