### PR TITLE
💄 Replace the search button with a magnifying glass 

### LINKED ISSUE #450: 💄 Replace the search button with a magnifying glass
#### Work Expected From the Issue
Replace the search button in the search page and the homepage with a magnifying glass.

#### Reason Behind the Change
Improve the search engine UI, making it look more modern and appealing to the user. Thus improving the user experience.

### Do you want to work on this issue?

None

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by loikx**
## What does this PR do?

This pr improve design of search bar with replacing search button with magnification glass.

## Why is this change important?

Improve UI, make it look more modern, improve the user experience

## Related issues

Closes #450

### CODE REVIEW

**Review by neon-mmd — CHANGES_REQUESTED** [review]
Thanks :heart: for working on this PR. We really appreciate it :+1: everything looks good but I think the magnifying glass color might not work on dark colorschemes like for example I think it might become invisible on colorscheme like `dark-chocolate`. So I would suggest using a magnifying glass image of different color or maybe you can also change the image dynamically by taking the svg code and putting it in the HTML file directly and then changing the `fillproperty` of svg image to change image colors dynamically. :slightly_smiling_face:

**Comment by loikx** [comment]
Thaks for such positive feedback, but I'm not clear about color change. I've checked all themes with black color. So if I need to change image color, what color I need to pick?

### Dark Chocolate
Снимок экрана 2024-01-05 в 20 56 29

### Solarized DarK
Снимок экрана 2024-01-05 в 20 59 01

### Tomorrow Night
Снимок экрана 2024-01-05 в 21 00 05

### Tokyo Night
Снимок экрана 2024-01-05 в 21 00 54

**Comment by neon-mmd** [comment]
> Thaks for such positive feedback, but I'm not clear about color change. I've checked all themes with black color. So if I need to change image color, what color I need to pick?
> 
> ### Dark Chocolate
> Снимок экрана 2024-01-05 в 20 56 29
> ### Solarized DarK
> Снимок экрана 2024-01-05 в 20 59 01
> ### Tomorrow Night
> Снимок экрана 2024-01-05 в 21 00 05
> ### Tokyo Night
> Снимок экрана 2024-01-05 в 21 00 54

After through testing, all the color schemes on our side. We found that the icon you have chosen works on all the color schemes, and as such we would suggest leaving the icon as it is. :slightly_smiling_face:

**Review by neon-mmd — DISMISSED** [review]
Thanks :heart: again for working on this PR. Since everything looks good. We will merge the PR right away :rocket: :slightly_smiling_face:

**Review by neon-mmd — APPROVED** [review]
Thanks :heart: again for working on this PR. Since everything looks good. We will merge the PR right away :rocket: :slightly_smiling_face:

**Pull request merged**
