### PR TITLE
UPDATED: Removed Deprecated API

### PR DESCRIPTION
**Pull request by LX5321**
Merges to `rolling` branch as per #61

### CODE REVIEW

**Comment by neon-mmd** [comment]
@LX5321 Thanks for taking the time to work on this.
I love this change :+1: well done!! and I am willing to have it merged but if you don't mind can you please refork the repo and add the changes to the new fork and reopen this PR :slightly_smiling_face: .

**Review by XFFXFF — APPROVED** [review]
Looks good to me!  Thanks for your contribution

**Comment by xffxff** [comment]
> Thanks for taking the time to work on this.
> I love this change 👍 well done!! and I am willing to have it merged but if you don't mind can you please refork the repo and add the changes to the new fork and reopen this PR 🙂

Everything looks good now, should we merge it? What do you think? @neon-mmd

**Comment by neon-mmd** [comment]
> > Thanks for taking the time to work on this.
> > I love this change +1 well done!! and I am willing to have it merged but if you don't mind can you please refork the repo and add the changes to the new fork and reopen this PR slightly_smiling_face
> 
> Everything looks good now, should we merge it? What do you think? @neon-mmd

Since it has no problems let's merge this :rocket: . so from my side, it is a *yes* :+1:.

**Pull request merged**
