### PR TITLE
📝 Increase the readability of Markdown documents 

### PR DESCRIPTION
**Pull request by Sweetdevil144**
## What does this PR do?

This PR is aimed at making increasing the readibility od all the markdown files in the project.

## Why is this change important?
It is important to help convey the goals and message of the Project

### CODE REVIEW

**Comment by Sweetdevil144** [comment]
I have drafted the pull request. I'll update all the files and notify you once everything is done the the PR is set to merge.

**Comment by neon-mmd** [comment]
Thanks ❤️ for working on this. We really appreciate it 👍🏻 keep it up!! But it seems that you are updating the `code of conduct` file which is a very sensitive file so I would rather suggest first having a thorough and serious discussion on this topic by opening an issue before you make any changes to it 🙂 .

**Comment by Sweetdevil144** [comment]
Sure @neon-mmd . I'm opening up an issue on the same for further discussions on updations and checks of other files so you can review it easier.

**Comment by Sweetdevil144** [comment]
Links to #264 .

**Comment by Sweetdevil144** [comment]
Hello @neon-mmd . Unfortunately, I won't be able to complete the docs for now. Can you please assign it to someone else or yourself?
Thank You.

**Comment by neon-mmd** [comment]
> Hello @neon-mmd . Unfortunately, I won't be able to complete the docs for now. Can you please assign it to someone else or yourself? Thank You.

Thanks :heart: for informing us, but I would suggest not leaving the work because this PR is still a draft, which means that you can work on it at whatever time you want. So I would suggest don't hurry, you can complete at any point in time. :slightly_smiling_face:

**Comment by Sweetdevil144** [comment]
Okay, sure !! I'll submit it soon then ! 😊

**Pull request closed without merging**
